import '../globals.css';
import Image from 'next/image';
import downloadImage from '../../img/logo.png';


export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
      <div className="flex flex-col justify-center items-center min-h-screen bg-image">
        <div className="p-5">
          <Image src={downloadImage} alt="Download Image" width={250} height={250} />
        </div>
        <div>
          {children}
        </div>
      </div>
      </body>
    </html>
  )
}
