import type { Metadata } from "next";
import Sidebar from '../../components/sidebar';
import { getServerSession } from "next-auth";
import authConfig from '../../auth.config';
import '../globals.css';

export const metadata: Metadata = {
  title: "Timperio",
  description: "Generated by create next app",
};

// Server component
export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // Fetch the session directly in the server component
  const session = await getServerSession(authConfig);
  const userRole = session?.account?.role || null;

  return (
    <html lang="en">
      <body>
        <div className="flex min-h-screen">
          {/* Only render Sidebar if role is defined */}
          {userRole && <Sidebar role={userRole} />}
          
          {/* Main Content */}
          <div className="flex-1 flex flex-col">
            <main className="flex-1 bg-gray-100">
              {children}
            </main>
          </div>
        </div>
      </body>
    </html>
  );
}
